/**
 * Mock data for Phase 1 scaffolding.
 *
 * Replace with real Server Actions wrapping the pipeline in Phase 2.
 * Keep this file around as fixture data for tests + Storybook-style demos.
 */

import type {
  HarnessCard,
  HarnessFact,
  HarnessCandidate,
  FinalPick,
  CardDetailView,
  StageState,
  AgreementSnapshot,
} from './types';

const NOW = '2026-05-19T18:30:00Z';
const EARLIER = '2026-05-19T18:00:00Z';
const EARLIEST = '2026-05-19T17:30:00Z';

export const MOCK_CARDS: HarnessCard[] = [
  {
    id: 'card-spot-hyperliquid-2026-05-19',
    voice: 'infinex',
    brief: 'Spot trading on Hyperliquid is now live in Infinex.',
    status: 'in-progress',
    created_at: EARLIEST,
    completed_at: null,
    research_approved_at: EARLIER,
    card_approved_at: NOW,
    ship_at: null,
  },
  {
    id: 'card-trezor-2026-05-19',
    voice: 'infinex',
    brief: 'Trezor hardware wallet support is now live.',
    status: 'shipped',
    created_at: '2026-05-19T14:00:00Z',
    completed_at: '2026-05-19T15:20:00Z',
    research_approved_at: '2026-05-19T14:20:00Z',
    card_approved_at: '2026-05-19T14:40:00Z',
    ship_at: '2026-05-19T15:20:00Z',
  },
  {
    id: 'card-private-send-beta-2026-05-18',
    voice: 'infinex',
    brief: 'Private Send beta opens to all users.',
    status: 'abandoned',
    created_at: '2026-05-18T11:00:00Z',
    completed_at: '2026-05-18T11:45:00Z',
    research_approved_at: null,
    card_approved_at: null,
    ship_at: null,
  },
];

const TRACKED_CARD_ID = MOCK_CARDS[0].id;

export const MOCK_FACTS: HarnessFact[] = [
  {
    id: 'fact-1',
    card_id: TRACKED_CARD_ID,
    category: 'partner',
    claim: 'spot venue provider',
    value: 'Hyperliquid',
    source: 'partner-registry',
    source_ref: 'src/fact-grounder/sources/partner-registry.ts:42',
    confidence: 0.95,
    verified_at: EARLIEST,
    status: 'approved',
    rejection_reason: null,
    created_by: 'grounder',
  },
  {
    id: 'fact-2',
    card_id: TRACKED_CARD_ID,
    category: 'number',
    claim: 'minimum order size',
    value: '$10',
    source: 'platform-code',
    source_ref: 'apps/spot/config.ts:14',
    confidence: 0.92,
    verified_at: EARLIEST,
    status: 'approved',
    rejection_reason: null,
    created_by: 'grounder',
  },
  {
    id: 'fact-3',
    card_id: TRACKED_CARD_ID,
    category: 'chain',
    claim: 'supported network',
    value: 'Arbitrum',
    source: 'platform-code',
    source_ref: 'apps/spot/networks.ts:8',
    confidence: 0.90,
    verified_at: EARLIEST,
    status: 'edited', // operator edited the source_ref
    rejection_reason: null,
    created_by: 'grounder',
  },
  {
    id: 'fact-4',
    card_id: TRACKED_CARD_ID,
    category: 'capability',
    claim: 'orderbook signature',
    value: 'native (not bolted on)',
    source: 'infinex-page',
    source_ref: 'https://infinex.xyz/perps',
    confidence: 0.85,
    verified_at: EARLIEST,
    status: 'pending',
    rejection_reason: null,
    created_by: 'grounder',
  },
  {
    id: 'fact-5',
    card_id: TRACKED_CARD_ID,
    category: 'capability',
    claim: 'launch hashtag',
    value: '#SpotIsLive',
    source: 'web-search',
    source_ref: 'inferred from recent campaigns',
    confidence: 0.45,
    verified_at: EARLIEST,
    status: 'rejected',
    rejection_reason: 'ungrounded — no such hashtag is being run, operator declined',
    created_by: 'grounder',
  },
];

const RELEASE_CARD_JSON_SAMPLE = {
  id: 'spot-hyperliquid-2026-05-19',
  title: 'Spot trading on Hyperliquid is now live in Infinex',
  ship_date: '2026-05-19',
  audience: ['x', 'web', 'in-product'],
  deployed_facts: [
    'spot venue provider: Hyperliquid',
    'minimum order size: $10',
    'supported network: Arbitrum',
    'orderbook signature: native (not bolted on)',
  ],
  kind: 'launch-tier',
  headline: 'Spot trading on Hyperliquid is live in Infinex.',
  tier_reason: 'First spot venue integration alongside perps — completes wallet-as-trading-surface for both sides.',
};

export const MOCK_RELEASE_CARD_JSON = JSON.stringify(RELEASE_CARD_JSON_SAMPLE, null, 2);

export const MOCK_CANDIDATES: HarnessCandidate[] = [
  {
    id: 'cand-x-1',
    card_id: TRACKED_CARD_ID,
    channel: 'x-thread',
    attempt: 1,
    text:
      "Spot used to live in a different app from your perps. We've been taking that wall down section by section.\n\nSpot on Hyperliquid is live in Infinex.\nSame passkey, same orderbook style, alongside perps.\n\nThe routing layer was the hard part — we held it back until spot felt as native as perps.\n\nA few months from now you won't think about which venue your order lives on.",
    structured_json: JSON.stringify({
      kind: 'thread',
      tweets: [
        "Spot used to live in a different app from your perps. We've been taking that wall down section by section.",
        'Spot on Hyperliquid is live in Infinex. Same passkey, same orderbook style, alongside perps.',
        'The routing layer was the hard part — we held it back until spot felt as native as perps.',
        "A few months from now you won't think about which venue your order lives on.",
      ],
    }),
    declared_beats_json: JSON.stringify([
      { tempo: 'sombre' }, { tempo: 'commanding' }, { tempo: 'practical' }, { tempo: 'irradiant' },
    ]),
    beat_audit_json: JSON.stringify([
      { beat_index: 0, declared_tempo: 'sombre', classified_tempo: 'sombre', classified_confidence: 0.57, passed: true },
      { beat_index: 1, declared_tempo: 'commanding', classified_tempo: 'commanding', classified_confidence: 0.47, passed: true },
      { beat_index: 2, declared_tempo: 'practical', classified_tempo: 'practical', classified_confidence: 0.60, passed: true },
      { beat_index: 3, declared_tempo: 'irradiant', classified_tempo: 'irradiant', classified_confidence: 0.42, passed: true },
    ]),
	    validation_passed: true,
	    validation_failures_json: '[]',
	    active_validation_passed: null,
	    active_audit_json: null,
	    history_guard_passed: null,
	    history_guard_json: null,
	    director_audit_id: null,
	    director_passed: null,
	    director_audit_json: null,
	    rationale: 'Full 4-beat launch-tier arc. All beats classified to declared tempo.',
    source: 'anthropic',
    prompt_variant: null,
    created_at: NOW,
  },
  {
    id: 'cand-x-2',
    card_id: TRACKED_CARD_ID,
    structured_json: null,
    channel: 'x',
    attempt: 1,
    text:
      'Spot venues used to fragment by app.\n\nSpot on Hyperliquid is live in Infinex. One portfolio, one passkey, perps and spot side by side.\n\nIn a year you won\'t remember which venue you started on.',
    declared_beats_json: JSON.stringify([
      { tempo: 'sombre' }, { tempo: 'commanding' }, { tempo: 'irradiant' },
    ]),
    beat_audit_json: JSON.stringify([
      { beat_index: 0, declared_tempo: 'sombre', classified_tempo: 'sombre', classified_confidence: 0.51, passed: true },
      { beat_index: 1, declared_tempo: 'commanding', classified_tempo: 'commanding', classified_confidence: 0.49, passed: true },
      { beat_index: 2, declared_tempo: 'irradiant', classified_tempo: 'sombre', classified_confidence: 0.31, passed: false },
    ]),
	    validation_passed: false,
	    validation_failures_json: JSON.stringify([
	      { rule: 'beat-tempo-fit', reason: 'beat 2 (declared irradiant): classified as sombre (confidence 0.31)' },
	    ]),
	    active_validation_passed: null,
	    active_audit_json: null,
	    history_guard_passed: null,
	    history_guard_json: null,
	    director_audit_id: null,
	    director_passed: null,
	    director_audit_json: null,
	    rationale: 'Tighter 3-beat shape. Closing beat read as Sombre rather than Irradiant.',
    source: 'anthropic',
    prompt_variant: null,
    created_at: NOW,
  },
  {
    id: 'cand-web-1',
    card_id: TRACKED_CARD_ID,
    structured_json: null,
    channel: 'web',
    attempt: 1,
    text: 'Spot on Hyperliquid. One account, one portfolio, alongside perps.',
    declared_beats_json: JSON.stringify([{ tempo: 'commanding' }]),
    beat_audit_json: JSON.stringify([
      { beat_index: 0, declared_tempo: 'commanding', classified_tempo: 'commanding', classified_confidence: 0.62, passed: true },
    ]),
	    validation_passed: true,
	    validation_failures_json: '[]',
	    active_validation_passed: null,
	    active_audit_json: null,
	    history_guard_passed: null,
	    history_guard_json: null,
	    director_audit_id: null,
	    director_passed: null,
	    director_audit_json: null,
	    rationale: 'Web-card length — single beat, declarative.',
    source: 'anthropic',
    prompt_variant: null,
    created_at: NOW,
  },
  {
    id: 'cand-inproduct-1',
    card_id: TRACKED_CARD_ID,
    structured_json: null,
    channel: 'in-product',
    attempt: 1,
    text: 'Spot on Hyperliquid is live.',
    declared_beats_json: JSON.stringify([{ tempo: 'commanding' }]),
    beat_audit_json: JSON.stringify([
      { beat_index: 0, declared_tempo: 'commanding', classified_tempo: 'commanding', classified_confidence: 0.71, passed: true },
    ]),
	    validation_passed: true,
	    validation_failures_json: '[]',
	    active_validation_passed: null,
	    active_audit_json: null,
	    history_guard_passed: null,
	    history_guard_json: null,
	    director_audit_id: null,
	    director_passed: null,
	    director_audit_json: null,
	    rationale: 'In-product modal header — minimum-viable copy.',
    source: 'anthropic',
    prompt_variant: null,
    created_at: NOW,
  },
];

export const MOCK_PICKS: FinalPick[] = [];

const STAGE_STATES: Record<string, StageState> = {
  research: {
    stage: 'research',
    status: 'approved',
    started_at: EARLIEST,
    completed_at: EARLIER,
    notes: null,
  },
  card: {
    stage: 'card',
    status: 'approved',
    started_at: EARLIER,
    completed_at: NOW,
    notes: 'Edited deployed_facts[3] to add "(not bolted on)" qualifier.',
  },
  generate: {
    stage: 'generate',
    status: 'awaiting',
    started_at: NOW,
    completed_at: null,
    notes: null,
  },
  ship: {
    stage: 'ship',
    status: 'pending',
    started_at: null,
    completed_at: null,
    notes: null,
  },
};

export function getMockCardDetail(cardId: string): CardDetailView | null {
  const card = MOCK_CARDS.find((c) => c.id === cardId);
  if (!card) return null;
  const facts = MOCK_FACTS.filter((f) => f.card_id === cardId);
  const candidates = MOCK_CANDIDATES.filter((c) => c.card_id === cardId);
  return {
    card,
    stages: {
      research: STAGE_STATES.research,
      card: STAGE_STATES.card,
      generate: STAGE_STATES.generate,
      ship: STAGE_STATES.ship,
    },
    facts,
    expected_channels: ['x', 'x-thread', 'web', 'in-product', 'modal', 'blog', 'carousel', 'image-brief'],
    candidates_by_channel: {
      x: candidates.filter((c) => c.channel === 'x'),
      'x-thread': candidates.filter((c) => c.channel === 'x-thread'),
      web: candidates.filter((c) => c.channel === 'web'),
      'in-product': candidates.filter((c) => c.channel === 'in-product'),
      modal: candidates.filter((c) => c.channel === 'modal'),
      blog: candidates.filter((c) => c.channel === 'blog'),
      carousel: candidates.filter((c) => c.channel === 'carousel'),
      'image-brief': candidates.filter((c) => c.channel === 'image-brief'),
    },
    attempts_by_channel: {
      x: [],
      'x-thread': [],
      web: [],
      'in-product': [],
      modal: [],
      blog: [],
      carousel: [],
      'image-brief': [],
    },
    actor_attempts: [],
    operator_feedback: [],
    pipeline_run: null,
    picks: MOCK_PICKS.filter((p) => p.card_id === cardId),
    pending_api_requests: [],
  };
}

// ─── Agreement metrics mock ─────────────────────────────────────────────────

export const MOCK_AGREEMENT: AgreementSnapshot[] = [
  {
    id: 'snap-1',
    snapshot_at: NOW,
    window_days: 7,
    voice: 'infinex',
    stage: 'research',
    beat_name: null,
    fact_source: null,
    agreement_rate: 0.83,
    sample_size: 24,
    approved_as_is: 20,
    edited: 3,
    rejected: 1,
  },
  {
    id: 'snap-2',
    snapshot_at: NOW,
    window_days: 7,
    voice: 'infinex',
    stage: 'card',
    beat_name: null,
    fact_source: null,
    agreement_rate: 0.71,
    sample_size: 14,
    approved_as_is: 10,
    edited: 4,
    rejected: 0,
  },
  {
    id: 'snap-3',
    snapshot_at: NOW,
    window_days: 7,
    voice: 'infinex',
    stage: 'generate',
    beat_name: null,
    fact_source: null,
    agreement_rate: 0.58,
    sample_size: 36,
    approved_as_is: 21,
    edited: 10,
    rejected: 5,
  },
  // Per-beat drill-down for the generate stage
  {
    id: 'snap-4',
    snapshot_at: NOW,
    window_days: 7,
    voice: 'infinex',
    stage: 'generate',
    beat_name: 'sombre',
    fact_source: null,
    agreement_rate: 0.91,
    sample_size: 22,
    approved_as_is: 20,
    edited: 2,
    rejected: 0,
  },
  {
    id: 'snap-5',
    snapshot_at: NOW,
    window_days: 7,
    voice: 'infinex',
    stage: 'generate',
    beat_name: 'commanding',
    fact_source: null,
    agreement_rate: 0.86,
    sample_size: 22,
    approved_as_is: 19,
    edited: 2,
    rejected: 1,
  },
  {
    id: 'snap-6',
    snapshot_at: NOW,
    window_days: 7,
    voice: 'infinex',
    stage: 'generate',
    beat_name: 'practical',
    fact_source: null,
    agreement_rate: 0.32,
    sample_size: 22,
    approved_as_is: 7,
    edited: 11,
    rejected: 4,
  },
  {
    id: 'snap-7',
    snapshot_at: NOW,
    window_days: 7,
    voice: 'infinex',
    stage: 'generate',
    beat_name: 'irradiant',
    fact_source: null,
    agreement_rate: 0.59,
    sample_size: 22,
    approved_as_is: 13,
    edited: 7,
    rejected: 2,
  },
];
