import { z } from "zod";

export const dataPartSchemas = {
  "agent-status": z.object({ text: z.string() }),
  "phase-progress": z.object({
    phase: z.string(),
    turn_id: z.number().nullable().optional(),
    event_seq: z.number().nullable().optional(),
  }),
  "file-changes": z.object({
    changes: z.array(z.object({ path: z.string(), kind: z.string() })),
    event_seq: z.number().nullable().optional(),
  }),
  "shell-command": z.object({
    command: z.string(),
    output: z.unknown().optional(),
    exitCode: z.number().nullable().optional(),
    exit_code: z.number().nullable().optional(),
    status: z.string().nullable().optional(),
    event_seq: z.number().nullable().optional(),
  }),
  "subagent": z.object({
    subagent_id: z.string().nullable().optional(),
    phase: z.string().nullable().optional(),
    status: z.string(),
    name: z.string().nullable().optional(),
    summary: z.string().nullable().optional(),
    error: z.string().nullable().optional(),
    activity: z.string().nullable().optional(),
    tool_name: z.string().nullable().optional(),
    activities: z
      .array(
        z.object({
          description: z.string(),
          toolName: z.string().optional(),
        }),
      )
      .nullable()
      .optional(),
    branch_index: z.number().nullable().optional(),
    total_branches: z.number().nullable().optional(),
    completed: z.number().nullable().optional(),
    acceptable: z.union([z.number(), z.boolean()]).nullable().optional(),
    failed: z.number().nullable().optional(),
    completed_count: z.number().nullable().optional(),
    acceptable_count: z.number().nullable().optional(),
    failed_count: z.number().nullable().optional(),
    is_acceptable: z.boolean().nullable().optional(),
    turns: z.number().nullable().optional(),
    tool_calls: z.number().nullable().optional(),
    duration_s: z.number().nullable().optional(),
    max_parallel: z.number().nullable().optional(),
    input_tokens: z.number().nullable().optional(),
    output_tokens: z.number().nullable().optional(),
    total_tokens: z.number().nullable().optional(),
    cost_usd: z.number().nullable().optional(),
    model: z.string().nullable().optional(),
    event_seq: z.number().nullable().optional(),
  }),
  "user-message": z.object({
    id: z.string(),
    turn_id: z.number(),
    text: z.string(),
    source: z.string().optional(),
    user_id: z.string().nullable().optional(),
    created_at: z.string().optional(),
    event_seq: z.number().nullable().optional(),
  }),
  "context-message": z.object({
    id: z.string(),
    turn_id: z.number(),
    text: z.string(),
    source: z.string().optional(),
    user_id: z.string().nullable().optional(),
    created_at: z.string().optional(),
    event_seq: z.number().nullable().optional(),
  }),
  "system-event": z.object({
    title: z.string(),
    text: z.string(),
    tone: z.enum(["info", "warn"]).optional(),
    event_seq: z.number().nullable().optional(),
  }),
  "token-usage": z.object({
    input_tokens: z.number().nullable().optional(),
    output_tokens: z.number().nullable().optional(),
    total_tokens: z.number(),
    cost_usd: z.number().nullable().optional(),
    quality: z.enum(["authoritative", "estimated"]).optional(),
    breakdown: z.enum(["known", "unknown"]).optional(),
    models: z.array(z.string()).optional(),
  }),
  "handoff": z.object({
    new_thread_key: z.string(),
    follow: z.boolean(),
    goal: z.string().optional(),
  }),
} as const;
